export type Customer = {
  accountId?: string | null;
  legalName?: string | null;
  dba?: string | null;
  licenseNumber?: string | null;
  status?: string | null;
  entityType?: string | null;
  agentId?: string | null;
  policyCount?: number | null;
  // Compatibility aliases for cached profiles created before the PBIA client API migration.
  databaseId?: string | null;
  commercialName?: string | null;
  fullName?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  type?: number | null;
  addressLine1?: string | null;
  addressLine2?: string | null;
  city?: string | null;
  stateNameOrAbbreviation?: string | null;
  zipCode?: string | null;
  email?: string | null;
  phone?: string | null;
  cellPhone?: string | null;
  smsPhone?: string | null;
  description?: string | null;
  website?: string | null;
  fein?: string | null;
  customerId?: string | null;
  insuredId?: string | null;
  active?: boolean;
};

export type CustomerLookupRecord = {
  accountId?: string;
  legalName?: string;
  dba?: string | null;
  email?: string | null;
  licenseNumber?: string | null;
  status?: string;
  entityType?: string | null;
  agentId?: string | null;
  policyCount?: number;
  databaseId: string;
  commercialName: string | null;
  firstName: string | null;
  lastName: string | null;
  type: number | null;
  addressLine1: string | null;
  addressLine2: string | null;
  stateNameOrAbbreviation: string | null;
  city: string | null;
  zipCode: string | null;
  eMail: string | null;
  eMail2: string | null;
  eMail3: string | null;
  fax: string | null;
  phone: string | null;
  cellPhone: string | null;
  smsPhone: string | null;
  description: string | null;
  active: boolean;
  website: string | null;
  fein: string | null;
  customerId: string | null;
  insuredId: string | null;
};
